/* eslint-disable @typescript-eslint/no-require-imports */
const { execSync } = require('child_process');
const fs = require('fs');
const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
const commit = execSync('git rev-parse HEAD').toString().trim();

const content = `// Auto-generated by genGitInfo.js
export const GIT_BRANCH = '${branch}';
export const GIT_COMMIT = '${commit}';
`;

fs.writeFileSync('src/gitInfo.ts', content);
// eslint-disable-next-line no-console
console.log('src/gitInfo.ts generated.');
